### ISSUE TITLE
ub_list warning

### ISSUE THREAD

**Issue by attuska** [uhulinux/uhubuild#3]
Újabban ez van sok fordításnál:
>addons...
>/usr/bin/ub_list: 23. sor: shift: shift-szám kívül esik a tartományon
>/usr/bin/ub_list: 30. sor: shift: shift-szám kívül esik a tartományon

**Comment by rezso** [comment]
Az ub_cp ub_list hívásánál van a gond valószínűleg, mivel ez csak az addons lépésben jön elő, az uhubuild-check futásakor, ahol szintén van ub_list hívás, nincs gond.

**Comment by rezso** [comment]
https://github.com/uhulinux/uhubuild/commit/174833a71ff97a0573b55e331b6dfd3aaf9f8755
