### ISSUE TITLE
autodepend bug?

### ISSUE THREAD

**Issue by attuska** [uhulinux/uhubuild#4]
Az fltk-dev_1.3.4~2-1.1_amd64.ubk3.uhu csomaggal forgatva autopend:
>attila@attila-pc:/usr/src/UHUBUILD/UB-UBK3$ dpkg-deb -I jwm-settings-manager_2.1.5-1.1_amd64.ubk3.uhu | grep fltk
 Depends: bash, fltk (>= 1.3.4), gcc-libs (>= 8.2.0), glibc (>= 2.26), libstdc++ (>= 8.2.0), libx11 (>= 1.6.7), libxpm (>= 3.5.12), pcmanfm, uhu-pkg
attila@attila-pc:/usr/src/UHUBUILD/UB-UBK3$ 

A depends-be belevéve: fltk
>attila@attila-pc:/usr/src/UHUBUILD/packages-UBK3/amd64$ dpkg-deb -I jwm-settings-manager_2.1.5-1.2_amd64.ubk3.uhu | grep fltk
 Depends: bash, fltk, gcc-libs (>= 8.2.0), glibc (>= 2.26), libstdc++ (>= 8.2.0), libx11 (>= 1.6.7), libxpm (>= 3.5.12), pcmanfm, uhu-pkg
attila@attila-pc:/usr/src/UHUBUILD/packages-UBK3/amd64$

**Comment by rezso** [comment]
Most mi a gond?

**Comment by attuska** [comment]
Az 1.3.4~2 az apt szerint nagyobb, mint az 1.3.4.
Az autodepend meg 1.3.4 et drótoz be 1.3.4~2 helyett a csomagba, a ~ -et már nem veszi figyelembe, hanem elhagyja az utána következőkkel együtt, azt egyszerűen exrarelease résznek tekinti, holott nem az.

**Comment by rezso** [comment]
Egyrészt az 1.3.4~2 elvileg kisebb, mint az 1.3.4, és szerintem épp ez az, ami gond: ha a függőség >= 1.3.4, akkor azt az 1.3.4~2 nem teljesíti.
Ha viszont  az 1.3.4~2 valóban nagyobb, mint az 1.3.4, akkor a >= 1.3.4 feltétel teljesül, és az apt/dpkg kezeli rosszul.
Én leginkább verziószám gondnak látom, ~ helyett + kellene.

**Comment by attuska** [comment]
Az 1.3.4~2 az u2d és az acquire módosításai, a forrás eredeti verziószáma 1.3.4-2, ami valóban nagyobb, mint az 1.3.4.
Ezt a kötőjeles verziószámot viszont az uhubuild-check hibásnak véli a - jel miatt, eddig ezt én mindenütt ezért ~ jellell helyettesítettem mind az u2d -ben, mind az acqure fájlban.
A jövőben a ~ helyett a + használata talán tényleg egyszerűbb, mint az uhubuild szkript módosítása, de ekkor minden olyan csomagunknál, ahol a verziószámban most ~ van, meg kell ezt a váltást lépni.

**Comment by rezso** [comment]
Na azzal azért csak óvatosan. Lehetnek olyan csomagok, ahol valóban ~ kell, nem +.
